# Generated by Django 4.0.6 on 2022-08-02 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.directionmedicine')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['id'],
            },
        ),
    ]
