# Generated by Django 4.0.6 on 2022-08-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionmedicine',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='directionmedicine',
            table='direction_medicine',
        ),
    ]
